export default {
    PRODUCT_FIELD: 'PRODUCT_FIELD',
    CUSTOMER_FIELD : 'CUSTOMER_FIELD',
    DATE_FIELD: 'DATE_FIELD',
    TEXT_FIELD: 'TEXT_FIELD',
    STOCKROOM_FIELD: 'STOCKROOM_FIELD',
    CHECKBOX_FIELD: 'CHECKBOX_FIELD'
};